### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-final-bis-modulo-1-MariaMunozR#6]
Hola @MariaMunozR, has hecho un buen trabajo pero me gustaría que intentases algunas mejoras:

## HTML

- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/index.html#L15 y https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/partials/_header.html#L1 Tenemos un header dentro de otro header. Lo ideal es tener solo uno de los dos. Es mejor dejar el del partial y quitar el del index.html para que así el header esté dentro del partial header que parece más coherente. Nos está pasando lo mismo con el main y footer.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/index.html#L9: pon el link de fuentes antes que el tuyo, de esta forma si quisieras puedes sobre escribir los estilos del css de fuentes.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/partials/_header.html#L11 Este `li` y este `a` tienen un fallo, sabrías decirme cuál.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/partials/_header.html#L15 Este `li` y este `a` tienen el mismo fallo de antes.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/templates/partials/_header.html#L11 Los textos en el HTML deben ser Blog y Contacto. Los debemos poner en mayúsculas con estilos CSS.
- [x] Ponle `title` a al logo.
- [x] El texto en el HTML debe ser `Creando diversidad digital` y lo ponemos con la primera letra de cada palabra en mayúsculas con CSS.
- [x] Debemos tener poner cada etiqueta HTML en una línea para mejorar su legibilidad, en vez de: 
```html
<a href="https://adalab.es/" target="_blank" class="link-logo" title="ir a página de Adalab"><img src="./assets/images/adalab-logo.svg"
       alt="logo Adalab"/></a>
```
nos gusta más esto:
```html
<a href="https://adalab.es/" target="_blank" class="link-logo" title="ir a página de Adalab">
  <img src="./assets/images/adalab-logo.svg" alt="logo Adalab"/>
</a>
```

## CSS

- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/main.scss#L8 Estos estilos son de reset, deberían ir dentro de `reset.scss`
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/core/_links.scss Borra los ficheros que no utilizamos.
- [x] Nuestro primer `import` debería ser el de settings o variables. Para que podamos utilizar estas variables en el resto de ficheros.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/_footer.scss#L5 En el footer tenemos un flex dentro de otro flex, así como varias propiedades flex que o bien nos sobran o bien no se están aplicando en el lugar adecuado. Habría que ir probando qué propiedades podemos borrar.
- [x] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/_hero.scss#L14 No debemos usar 100vw salvo que necesitemos que el ancho de algo sea el mismo ancho que el de la ventana. Como primera opción debemos intentar no poner ancho, ya que casi siempre los elementos tienen un 100% de ancho por defecto. Y como segunda opción debemos ponerlo el 100% en porcentaje para que se ajuste al tamaño de su madre, no al de la ventana.
- [x] No es fácil ajustar la foto de fondo del main. Para ponerla bien debemos usar `background-position-x: 75%` e ir ajustándolo para cada media query.

Muchas gracias.

**Comment by MariaMunozR** [comment]
Creo que está todo. 
Igual no lo veo pero :  "Ponle title a al logo." estaba desde el principio.
Espero feedback. 
Gracias

**Comment by migueldelmazo** [comment]
Hola @MariaMunozR solo hay 3 cositas, las dos que he desmarcado arriba y esta de aquí.

- [ ] https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/_header.scss#L8 Esta propiedad creo que nos sobraría. 
- [x] Esto está perfecto https://github.com/Adalab/evaluacion-final-bis-modulo-1-MariaMunozR/blob/master/_src/assets/scss/_hero.scss#L9

Haciendo esto habrás alcanzado la perfección absoluta!!!
